"""
Static phone dashboard for robinhood_screener — renders the committed data files into
docs/index.html, which GitHub Pages serves. Regenerated by the same Actions run that produced
the data, so the page is exactly as fresh as the last committed scan and never fresher.

WHY A STATIC RENDERER. The previous dashboard.py was a resident log-scraping HTTP server on
port 8899 that parsed run.out.log by regex; it showed whatever the log happened to say, needed
a launchd agent of its own, and could not run on the Actions runner at all. This file is the
solana_screener design: presentation-only, no network, no scoring, no state of its own — every
number on the page is read from a file another module committed (latest_scan.json, the ledger,
the paper A-book, the weekly livebook summary, run_log.jsonl).

Two rules that keep it honest:
  • no wall-clock in any compute path. The only timestamps shown come from committed data; the
    "updated N min ago" counter is client-side JS, and the "runs in the last 24 h" window is
    anchored on the LAST SCAN's scan_ts, not on now — so a page rendered from stale data says
    what the data says, and the client-side tripwire (red past 30 min) says it is stale.
  • it shows MEASURED cadence, never the nominal one. GitHub's `*/5` cron fired 13.7×/day on
    this account against a nominal 288 (measured 2026-09-12); the page counts run_log lines.

Every input is optional and degrades to an empty section with a reassurance rather than an
error — most scans have no A-tier coin, and that is the filter working. Never raises on bad
data: each section is built behind _safe(), so one malformed file cannot blank the page.
"""
from __future__ import annotations

import html
import json
import os
import statistics
import sys
import time

import pandas as pd

import config
import ledger

# ── module-level fallbacks (in config if/when the other agents add them) ──────────
STALE_MINUTES = config.KEEPER_STALE_S // 60   # the tripwire: red past 30 min (the keeper scans every 240 s)
META_REFRESH_S = 300          # the plan: meta refresh 300 s
RUNS_WINDOW_S = 86400         # "runs in the last 24 h", anchored on the last scan_ts
MAX_CARDS_PER_TIER = 40       # a page, not a log
_EMPTY = ("", "nan", "None", "NaN", "null")
_HOST_LABELS = (("dexscreener", "dexscreener"), ("geckoterminal", "geckoterminal"),
                ("blockscout", "blockscout"), ("rpc.", "rpc"), ("scanhood", "scanhood"),
                ("robinx", "robinx"), ("kyberswap", "kyber"))


# ── tolerant readers (every input is optional) ───────────────────────────────────
def _num(v, default=None):
    """float(v) or default; NaN / '' / None / garbage → default."""
    try:
        if v is None or str(v) in _EMPTY:
            return default
        f = float(v)
        return default if f != f else f
    except (TypeError, ValueError):
        return default


def _esc(v, n: int = 60) -> str:
    return html.escape(str(v if v is not None else "?")[:n])


def _read_json(path: str):
    """A dict/list from a JSON file, or None when missing or unreadable."""
    try:
        if path and os.path.exists(path) and os.path.getsize(path) > 0:
            with open(path) as f:
                return json.load(f)
    except Exception as exc:
        print(f"  [dashboard] {path} unreadable ({exc}); section left empty")
    return None


def _read_run_log(path: str) -> list:
    """run_log.jsonl → list of dicts; a corrupt line is skipped, never fatal."""
    out: list = []
    try:
        if not (path and os.path.exists(path)):
            return out
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                    if isinstance(d, dict):
                        out.append(d)
                except Exception:
                    continue
    except Exception as exc:
        print(f"  [dashboard] {path} unreadable ({exc})")
    return out


def _read_paper(ledger_path: str, positions_path: str) -> dict:
    """The paper A-book as {"fills": [row dicts], "positions": {key: {...}}}. Either file may be
    absent. The positions file may be the bare {key: pos} map or a wrapper carrying
    "positions" / "pending_buys" / "pending_exits"; both shapes are accepted."""
    fills: list = []
    try:
        if ledger_path and os.path.exists(ledger_path) and os.path.getsize(ledger_path) > 0:
            fills = pd.read_csv(ledger_path, dtype=str).fillna("").to_dict("records")
    except Exception as exc:
        print(f"  [dashboard] {ledger_path} unreadable ({exc})")
    positions: dict = {}
    raw = _read_json(positions_path)
    if isinstance(raw, dict):
        inner = raw.get("positions")
        if isinstance(inner, dict):
            positions = inner
        else:
            positions = {k: v for k, v in raw.items() if isinstance(v, dict)
                         and k not in ("pending_buys", "pending_exits")}
    return {"fills": fills, "positions": positions}


def load_inputs() -> tuple:
    """(scan, led, paper, live, run_log) from the committed files — all optional."""
    scan = _read_json(config.SCAN_PATH)
    if not isinstance(scan, dict):
        scan = {}
    try:
        led = ledger.load()
    except Exception as exc:
        print(f"  [dashboard] ledger unreadable ({exc}); scorecard left empty")
        led = pd.DataFrame(columns=ledger.COLUMNS)
    paper = _read_paper(config.PAPER_LEDGER_PATH, config.PAPER_POSITIONS_PATH)
    live = _read_json(config.LIVEBOOK_SUMMARY_PATH)
    if not isinstance(live, dict):
        live = None
    run_log = _read_run_log(config.RUN_LOG_PATH)
    return scan, led, paper, live, run_log


# ── formatting ───────────────────────────────────────────────────────────────────
def _fmt_usd(v) -> str:
    f = _num(v)
    if f is None:
        return "?"
    sign, a = ("-" if f < 0 else ""), abs(f)
    if a >= 1e9:
        return f"{sign}${a / 1e9:.1f}B"
    if a >= 1e6:
        return f"{sign}${a / 1e6:.1f}M"
    if a >= 1e3:
        return f"{sign}${a / 1e3:.0f}k"
    if a < 10 and a != 0:
        return f"{sign}${a:.2f}"          # gas and $10-position P&L live in the cents
    return f"{sign}${a:.0f}"


def _fmt_pct(v, signed: bool = False, digits: int = 0) -> str:
    f = _num(v)
    if f is None:
        return "?"
    return f"{f:+.{digits}f}%" if signed else f"{f:.{digits}f}%"


def _fmt_ret(v) -> str:
    """A ledger return (fraction) as a signed percent."""
    f = _num(v)
    return "·" if f is None else f"{f * 100:+.0f}%"


def _fmt_age(minutes) -> str:
    m = _num(minutes)
    if m is None:
        return "?"
    if m >= 1440:
        return f"{m / 1440:.1f}d"
    if m >= 90:
        return f"{m / 60:.1f}h"
    return f"{m:.0f}m"


def _fmt_secs(s) -> str:
    f = _num(s)
    if f is None:
        return "?"
    return f"{f:.0f}s" if f < 120 else f"{f / 60:.1f} min"


def _day(ts) -> str:
    """UTC day label for a COMMITTED timestamp (never the wall clock)."""
    f = _num(ts, 0.0)
    return time.strftime("%Y-%m-%d", time.gmtime(f))


def _host_label(host: str) -> str:
    h = str(host).lower()
    for needle, label in _HOST_LABELS:
        if needle in h:
            return label
    return h[:24]


def _safe(build, fallback: str = '<p class="note">section unavailable (malformed data)</p>') -> str:
    """Build one section; a malformed input degrades that section, never the page."""
    try:
        return build()
    except Exception as exc:
        print(f"  [dashboard] section failed: {exc!r}")
        return fallback


# ── sections ─────────────────────────────────────────────────────────────────────
def _runs_line(scan: dict, run_log: list) -> str:
    """Measured cadence: run_log entries with scan_ts >= last scan_ts - 24 h, where the last
    scan_ts is the scan's own (or the newest run_log line) — never the wall clock."""
    entries = [e for e in (run_log or []) if isinstance(e, dict) and _num(e.get("scan_ts")) is not None]
    last_ts = _num((scan or {}).get("scan_ts"))
    if not last_ts and entries:
        last_ts = max(_num(e["scan_ts"]) for e in entries)
    if not last_ts or not entries:
        return ('<div class="stamp">runs in the last 24 h: none logged yet '
                '— the first committed run writes the run log</div>')
    lo = last_ts - RUNS_WINDOW_S
    recent = [e for e in entries if _num(e["scan_ts"]) >= lo]
    n = len(recent)
    by = {}
    for e in recent:
        by[str(e.get("trigger") or "?")] = by.get(str(e.get("trigger") or "?"), 0) + 1
    d, s = by.get("dispatch", 0), by.get("schedule", 0)
    other = n - d - s
    secs = [_num(e.get("run_seconds")) for e in recent]
    secs = [x for x in secs if x is not None]
    med = f" · median run {_fmt_secs(statistics.median(secs))}" if secs else ""
    n_a = sum(int(_num(e.get("n_a"), 0)) for e in recent)
    n_def = sum(1 for e in recent if _num(e.get("deferred"), 0))
    parts = [f"runs in the last 24 h: <b>{n}</b> (dispatch {d} / schedule {s}"
             + (f" / other {other}" if other else "") + f"){med}"]
    parts.append(f"A alerts {n_a}")
    if n_def:
        parts.append(f"{n_def} run(s) hit the time budget")
    return f'<div class="stamp">{" · ".join(parts)}</div>'


def _health_chips(scan: dict) -> str:
    health = (scan or {}).get("health") or {}
    if not isinstance(health, dict) or not health:
        chips = '<span class="chip unk">no source health recorded</span>'
    else:
        chips = ""
        for host, v in sorted(health.items()):
            v = v if isinstance(v, dict) else {}
            ok, fail = int(_num(v.get("ok"), 0)), int(_num(v.get("fail"), 0))
            if v.get("bot_challenge"):
                cls, tag = "bot", "BOT-CHALLENGED"
            elif fail and not ok:
                cls, tag = "dark", "DARK"
            elif fail:
                cls, tag = "deg", "degraded"
            else:
                cls, tag = "ok", "ok"
            detail = f"{ok} ok / {fail} failed / {int(_num(v.get('absent'), 0))} absent"
            if v.get("last_status"):
                detail += f", last HTTP {_esc(v.get('last_status'), 8)}"
            if v.get("blocked_reason"):
                detail += f", {_esc(v.get('blocked_reason'), 80)}"
            chips += (f'<span class="chip {cls}" title="{html.escape(detail, quote=True)}">'
                      f'{_esc(_host_label(host), 24)} {tag}</span>')
    na = _num((scan or {}).get("champion_na_frac"))
    na_line = ""
    if na and na > 0:
        na_line = (f'<p class="warn">champion band was NA (unknown inputs) on {na * 100:.0f}% of '
                   f'survivors this scan — an unknown is never A, so a dark source lowers the '
                   f'A count rather than faking one.</p>')
    return f'<div class="chips">{chips}</div>{na_line}'


def _card(s: dict, champion: str) -> str:
    sym = _esc(s.get("symbol"), 14)
    url = html.escape(str(s.get("url") or ""), quote=True)
    tier = "A" if s.get("tier") == "A" else "B"
    kind = _esc(s.get("event_kind") or "", 20)
    seq = s.get("event_seq")
    misses = s.get("hc_misses") or []
    miss_title = html.escape("; ".join(str(m) for m in misses[:4]), quote=True)
    badge = ('<span class="badge a">A-TIER</span>' if tier == "A"
             else f'<span class="badge b" title="{miss_title}">B</span>')
    kind_html = f'<span class="kind">{kind}{f" #{int(_num(seq, 0))}" if _num(seq) else ""}</span>' if kind else ""
    score = _num(s.get("score"), 0.0)
    holders = s.get("total_holders")
    hsrc = s.get("holders_source")
    holders_txt = ("?" if _num(holders) is None else f"{int(_num(holders))}") + \
                  (f" ({_esc(hsrc, 12)})" if hsrc else "")
    lp = _num(s.get("lp_locked_pct"))
    lp_txt = "unknown" if lp is None else f"{lp:.0f}%" + (f" ({_esc(s.get('lp_check_source'), 10)})"
                                                          if s.get("lp_check_source") else "")
    rt = s.get("roundtrip_loss_pct")
    dark = s.get("sources_dark") or []
    dark_html = (f'<div class="miss">dark: {_esc(", ".join(str(d) for d in dark), 80)}</div>'
                 if dark else "")
    if tier == "A":
        short = ""
    else:
        reason = s.get("champion_reason") or ("; ".join(str(m) for m in misses[:2]) if misses else "")
        short = (f'<div class="miss">short of {_esc(champion, 40)}: {_esc(reason, 160)}</div>'
                 if reason else "")
    plan = s.get("plan_line")
    plan_html = f'<div class="plan">{_esc(plan, 240)}</div>' if plan else ""
    bands = s.get("bands") or {}
    bands_html = ""
    if isinstance(bands, dict) and bands:
        fired = sorted(k for k, v in bands.items() if v in (1, True))
        na = sorted(k for k, v in bands.items() if v == "NA" or v is None)
        bits = []
        if fired:
            bits.append("✓ " + ", ".join(_esc(b, 24) for b in fired[:6]))
        if na:
            bits.append("NA " + ", ".join(_esc(b, 24) for b in na[:4]))
        if bits:
            bands_html = f'<div class="bands">bands: {" · ".join(bits)}</div>'
    tok = str(s.get("token") or "").lower()
    links = []
    if url:
        links.append(f'<a href="{url}" target="_blank" rel="noopener">dexscreener</a>')
    if tok:                                     # the terminal + explorer deep links, separate anchors
        gm = html.escape(config.GMGN_TOKEN_URL.format(chain=config.GMGN_CHAIN, token=tok), quote=True)
        bs = html.escape(config.BLOCKSCOUT_TOKEN_URL.format(token=tok), quote=True)
        links.append(f'<a href="{gm}" target="_blank" rel="noopener">gmgn</a>')
        links.append(f'<a href="{bs}" target="_blank" rel="noopener">explorer</a>')
    links_html = f'<div class="links">{" · ".join(links)}</div>' if links else ""
    return f"""
    <div class="card {'atier' if tier == 'A' else ''}">
      <div class="row1"><span class="sym">{sym}</span>{badge}{kind_html}
        <span class="score">{score:.0f}<small>/100</small></span></div>
      <div class="row2">
        <span>liq {_fmt_usd(s.get('liq_usd'))}</span><span>mcap {_fmt_usd(s.get('mcap'))}</span>
        <span>vol24 {_fmt_usd(s.get('vol_h24'))}</span><span>age {_fmt_age(s.get('pair_age_min'))}</span>
      </div>
      <div class="row2">
        <span>holders {holders_txt}</span><span>top10 {_fmt_pct(s.get('top10_pct'))}</span>
        <span>LP burned {lp_txt}</span><span>round-trip {_fmt_pct(rt, digits=1)}</span>
      </div>
      {short}{dark_html}{bands_html}{plan_html}{links_html}
    </div>"""


def _cards(survivors: list, tier: str, champion: str) -> str:
    rows = [s for s in survivors if isinstance(s, dict)
            and (("A" if s.get("tier") == "A" else "B") == tier)]
    rows.sort(key=lambda s: -(_num(s.get("score"), 0.0)))
    if not rows:
        if tier == "A":
            return ('<div class="empty">No A-tier coins this scan. Most scans have none — '
                    'that is the filter doing its job, not a malfunction.</div>')
        return ('<div class="empty">No B-tier survivors this scan — nothing passed the hard '
                'gates at this moment. On this chain that is the normal state.</div>')
    out = "".join(_card(s, champion) for s in rows[:MAX_CARDS_PER_TIER])
    if len(rows) > MAX_CARDS_PER_TIER:
        out += f'<p class="note">… and {len(rows) - MAX_CARDS_PER_TIER} more (see latest_scan.json)</p>'
    return out


def _discovery(scan: dict) -> str:
    sc = scan or {}
    by = sc.get("by_source") or {}
    cuts = sc.get("quota_cuts") or {}
    deferred = sc.get("deferred_by_stage") or {}
    rejects = sc.get("pass1_rejects_by_gate") or {}
    if not any((by, cuts, deferred, rejects)) and not _num(sc.get("discovered")):
        return '<p class="note">No discovery recorded yet — the first committed run fills this in.</p>'
    rows = ""
    for src in ("logs", "watchlist", "rechecks", "feeds"):
        if src in by or src in cuts:
            n = int(_num(by.get(src), 0))
            c = int(_num(cuts.get(src), 0))
            rows += (f"<tr><td>{src}</td><td>{n}</td>"
                     f"<td>{c if c else '·'}</td></tr>")
    for src in sorted(set(by) | set(cuts)):
        if src not in ("logs", "watchlist", "rechecks", "feeds"):
            rows += (f"<tr><td>{_esc(src, 20)}</td><td>{int(_num(by.get(src), 0))}</td>"
                     f"<td>{int(_num(cuts.get(src), 0)) or '·'}</td></tr>")
    table = (f"<table><tr><th>source</th><th>discovered</th><th>quota cut</th></tr>{rows}</table>"
             if rows else "")
    bits = []
    absent = _num(sc.get("absent"))
    if absent:
        bits.append(f"absent (no such pair/token): {int(absent)}")
    if isinstance(deferred, dict) and any(_num(v, 0) for v in deferred.values()):
        bits.append("time budget cut: " + ", ".join(
            f"{_esc(k, 20)} {int(_num(v, 0))}" for k, v in sorted(deferred.items()) if _num(v, 0)))
    if isinstance(rejects, dict) and any(_num(v, 0) for v in rejects.values()):
        top = sorted(((int(_num(v, 0)), k) for k, v in rejects.items() if _num(v, 0)), reverse=True)
        bits.append("pass-1 rejects by gate: " + ", ".join(f"{_esc(k, 24)} {n}" for n, k in top[:8]))
    notes = "".join(f'<p class="note">{b}</p>' for b in bits)
    return table + notes


def _scorecard(led: pd.DataFrame) -> str:
    """A vs B per horizon: n, hit-rate, median, dead %; then per-tier promoted-B n, alert-days,
    rugged-after and suspect counts. Mirrors ledger.summary()."""
    if led is None or len(led) == 0:
        return ('<p class="note">No ledger rows yet — every survivor gets a row from the first '
                'committed run; horizons fill over the following week.</p>'
                '<p class="note">If tier A doesn\'t clearly beat tier B, the A-band is not adding '
                'signal.</p>')
    d = led.copy()
    d["_tier"] = d["tier"].astype(str).where(d["tier"].astype(str).isin(["A", "B"]), "B")
    d["_ts"] = pd.to_numeric(d["alert_ts"], errors="coerce").fillna(0.0)
    d["_day"] = d["_ts"].apply(_day)
    live = d[~d["status"].astype(str).eq("suspect")]
    horizons = list(ledger.HORIZ)
    head = "".join(f"<th>{h}</th>" for h in horizons)
    body = ""
    tier_notes = ""
    for tier in ("A", "B"):
        sub = live[live["_tier"] == tier]
        label = "A (alerted)" if tier == "A" else "B (silent control)"
        if len(sub) == 0:
            body += f"<tr><td>{label}</td><td>0</td>{'<td>·</td>' * len(horizons)}</tr>"
            continue
        cells = ""
        for h in horizons:
            r = pd.to_numeric(sub[f"ret_{h}"], errors="coerce").dropna()
            if len(r):
                cells += (f"<td><b>{(r > 0).mean() * 100:.0f}%</b> / {r.median() * 100:+.0f}%"
                          f"<br><small>n={len(r)} · dead {(r <= -0.99).mean() * 100:.0f}%</small></td>")
            else:
                cells += "<td>·</td>"
        body += f"<tr><td>{label}</td><td>{len(sub)}</td>{cells}</tr>"
        days = int(sub["_day"].nunique())
        promoted = int((~ledger.empty_mask(sub["promoted_ts"])).sum())
        rugged = float(sub["rugged_after"].astype(str).str.lower().eq("true").mean())
        n_open = int((~sub["status"].astype(str).isin(["resolved", "suspect"])).sum())
        extra = f" · promoted-B n={promoted}" if tier == "B" else ""
        floor = ("" if days >= config.MIN_BOOTSTRAP_CLUSTERS else
                 f" · below {config.MIN_BOOTSTRAP_CLUSTERS} alert-days: not a bound")
        tier_notes += (f'<p class="note">tier {tier}: n={len(sub)} across {days} alert-day(s)'
                       f'{extra} · open {n_open} · rugged-after-passing-gates '
                       f'{rugged * 100:.0f}%{floor}</p>')
    n_sus = int(d["status"].astype(str).eq("suspect").sum())
    sus = (f'<p class="note">quote-integrity: {n_sus} row(s) terminally SUSPECT (implied supply '
           f'moved &gt;{config.SUPPLY_DRIFT_MAX}x vs entry) — excluded above, not "still maturing".</p>'
           if n_sus else "")
    return (f"<table><tr><th>tier</th><th>n</th>{head}</tr>{body}</table>"
            f'<p class="note">cells = hit-rate / median return once a horizon matures; dead = '
            f'return ≤ −99%. Promoted B rows stay in B (intention-to-treat).</p>'
            f"{tier_notes}{sus}"
            f'<p class="note"><b>If tier A doesn\'t clearly beat tier B, the A-band is not adding '
            f'signal.</b> A losing scorecard is the screen doing its job — telling you not to scale.</p>')


def _paper_book(paper: dict) -> str:
    fills = [f for f in ((paper or {}).get("fills") or []) if isinstance(f, dict)]
    positions = {k: v for k, v in dict((paper or {}).get("positions") or {}).items()
                 if isinstance(v, dict)}
    if not fills and not positions:
        return ('<p class="note">No paper fills yet — the A book opens a ~$'
                f'{config.STACK_USD * config.POSITION_PCT:.0f} paper position at a real quote for '
                'every A alert. Quotes only; nothing here touches keys or funds.</p>'
                '<p class="note">Real automation is justified ONLY if this scorecard is '
                'repeatedly positive.</p>')
    n_open = sum(1 for p in positions.values() if isinstance(p, dict) and not p.get("closed"))
    n_closed = sum(1 for p in positions.values() if isinstance(p, dict) and p.get("closed"))
    cost = sum(_num(p.get("cost_usd"), 0.0) for p in positions.values() if isinstance(p, dict))
    realized = sum(_num(p.get("realized_usd"), 0.0) for p in positions.values() if isinstance(p, dict))
    closed_cost = sum(_num(p.get("cost_usd"), 0.0) for p in positions.values()
                      if isinstance(p, dict) and p.get("closed"))
    closed_real = sum(_num(p.get("realized_usd"), 0.0) for p in positions.values()
                      if isinstance(p, dict) and p.get("closed"))
    buys = [f for f in fills if str(f.get("side", "")).lower().startswith("buy")]
    sells = [f for f in fills if str(f.get("side", "")).lower().startswith("sell")]
    impacts = [_num(f.get("impact_pct")) for f in buys]
    impacts = [x for x in impacts if x is not None]
    failed = sum(1 for f in fills if "_failed" in str(f.get("quote_status", "")) or
                 "failed" in str(f.get("note", "")).lower())
    gas = sum(_num(f.get("gas_usd"), 0.0) for f in fills)
    rows = [("positions", f"{n_open} open · {n_closed} closed"),
            ("fills", f"{len(buys)} buys · {len(sells)} sells" + (f" · {failed} failed" if failed else "")),
            ("cost (all)", _fmt_usd(cost)),
            ("realized (all)", f"{_fmt_usd(realized)}"),
            ("closed P&L", (f"{_fmt_usd(closed_real - closed_cost)} on {_fmt_usd(closed_cost)} "
                            f"({(closed_real / closed_cost - 1) * 100:+.0f}%)") if closed_cost > 0 else "·"),
            ("mean entry impact", f"{statistics.mean(impacts):.2f}% (n={len(impacts)})" if impacts else "·"),
            ("gas charged", _fmt_usd(gas))]
    table = "<table>" + "".join(f"<tr><th>{k}</th><td>{v}</td></tr>" for k, v in rows) + "</table>"
    return (table +
            '<p class="note">Paper fills at real aggregator quotes with slippage and L2 gas charged; '
            'realized includes only executed exits, open positions are NOT marked to market here.</p>'
            '<p class="note"><b>Real automation is justified ONLY if this scorecard is repeatedly '
            'positive.</b></p>')


def _livebook(live) -> str:
    if not isinstance(live, dict) or not live:
        return ('<p class="note">The live paper book runs on the Mac; a summary is published '
                'weekly.</p>')
    per = live.get("per_policy") or {}
    ctl = live.get("controls") or {}
    head = (f'<p class="stamp">as of {_esc(_day(live.get("ts")), 12)} · champion '
            f'{_esc(live.get("champion"), 40)} · {int(_num(live.get("n_positions"), 0))} positions '
            f'across {int(_num(live.get("n_days"), 0))} day(s)</p>')
    rows = ""
    if isinstance(per, dict) and per:
        order = sorted(per.items(), key=lambda kv: -(_num((kv[1] or {}).get("day_lb"), -1e9)
                                                     if isinstance(kv[1], dict) else -1e9))
        for name, v in order[:24]:
            v = v if isinstance(v, dict) else {}
            lb = _num(v.get("day_lb"))
            cls = ' class="pos"' if (lb is not None and lb > 0) else ""
            rows += (f"<tr{cls}><td>{_esc(name, 32)}</td><td>{int(_num(v.get('n'), 0))}</td>"
                     f"<td>{_fmt_ret(v.get('mean'))}</td><td>{_fmt_ret(lb)}</td></tr>")
    if isinstance(ctl, dict):
        for name, v in sorted(ctl.items()):
            v = v if isinstance(v, dict) else {}
            rows += (f'<tr class="ctl"><td>{_esc(name, 32)} (control)</td><td>{int(_num(v.get("n"), 0))}</td>'
                     f"<td>{_fmt_ret(v.get('mean'))}</td><td>{_fmt_ret(v.get('day_lb'))}</td></tr>")
    table = (f"<table><tr><th>policy</th><th>n</th><th>mean</th><th>day-clustered 2.5% LB</th></tr>"
             f"{rows}</table>" if rows else '<p class="note">no per-policy rows in the summary</p>')
    nom = live.get("nomination")
    nom_html = f'<p class="note">nomination: {_esc(nom if isinstance(nom, str) else json.dumps(nom), 200)}</p>' if nom else ""
    note = live.get("note")
    note_html = f'<p class="note">{_esc(note, 300)}</p>' if note else ""
    return (head + table + nom_html + note_html +
            '<p class="note">The decision criterion is the day-clustered 2.5th-percentile lower '
            'bound, never the mean; a control that clears it means the apparatus is measuring '
            'itself.</p>')


# ── the page ─────────────────────────────────────────────────────────────────────
_CSS = """
  :root { color-scheme: dark; }
  * { box-sizing: border-box; margin: 0; }
  body { background: #0d1117; color: #e6edf3; font: 16px/1.45 -apple-system, "SF Pro Text",
         Segoe UI, Roboto, sans-serif; padding: 16px; max-width: 640px; margin: 0 auto; }
  h1 { font-size: 20px; } h2 { font-size: 15px; color: #8b949e; margin: 22px 0 8px;
       text-transform: uppercase; letter-spacing: .06em; }
  .stamp { color: #8b949e; font-size: 13px; margin: 4px 0 8px; }
  .stamp b { color: #e6edf3; }
  .warn { color: #d29922; font-size: 13px; margin: 6px 0; }
  .chips { display: flex; flex-wrap: wrap; gap: 6px; margin: 6px 0; }
  .chip { font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 999px;
          background: #21262d; color: #8b949e; }
  .chip.ok { background: #1f3a2a; color: #3fb950; } .chip.deg { background: #3a2f12; color: #d29922; }
  .chip.dark { background: #3d1c1c; color: #f85149; } .chip.bot { background: #3d1c1c; color: #f85149;
  border: 1px solid #f85149; } .chip.unk { background: #21262d; }
  .card { display: block; background: #161b22; border: 1px solid #21262d; border-radius: 12px;
          padding: 12px 14px; margin-bottom: 10px; text-decoration: none; color: inherit; }
  .card.atier { border-color: #2ea043; box-shadow: 0 0 0 1px #2ea04355; }
  .row1 { display: flex; align-items: baseline; gap: 10px; flex-wrap: wrap; }
  .sym { font-weight: 700; font-size: 18px; }
  .kind { color: #8b949e; font-size: 12px; }
  .score { margin-left: auto; font-weight: 700; font-size: 18px; color: #58a6ff; }
  .score small { color: #8b949e; font-weight: 400; }
  .badge { font-size: 11px; font-weight: 700; padding: 2px 7px; border-radius: 999px; }
  .badge.a { background: #2ea043; color: #fff; } .badge.b { background: #30363d; color: #8b949e; }
  .row2 { display: flex; flex-wrap: wrap; gap: 4px 14px; color: #8b949e; font-size: 13px;
          margin-top: 6px; }
  .miss { color: #d29922; font-size: 12px; margin-top: 6px; }
  .links { font-size: 12px; margin-top: 6px; color: #8b949e; }
  .links a { color: #58a6ff; text-decoration: none; }
  .bands { color: #8b949e; font-size: 12px; margin-top: 4px; }
  .plan { color: #58a6ff; font-size: 12px; margin-top: 6px; }
  .empty { color: #8b949e; background: #161b22; border: 1px dashed #30363d; border-radius: 12px;
           padding: 14px; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 5px 6px; border-bottom: 1px solid #21262d; vertical-align: top; }
  th { color: #8b949e; font-weight: 600; }
  td small { color: #8b949e; }
  tr.pos td { color: #3fb950; } tr.ctl td { color: #6e7681; font-style: italic; }
  .note { color: #8b949e; font-size: 12px; margin-top: 8px; }
  footer { color: #6e7681; font-size: 12px; margin: 26px 0 8px; line-height: 1.5; }
"""

_JS = """
  const el = document.getElementById('ago'), ts = +el.dataset.ts * 1000,
        stale = +el.dataset.stale;
  function tick() {
    if (!ts) { el.textContent = 'no scan yet'; return; }
    const m = Math.max(0, Math.round((Date.now() - ts) / 60000));
    el.textContent = 'updated ' + (m < 60 ? m + ' min ago' : (m / 60).toFixed(1) + ' h ago');
    if (m > stale) { el.style.color = '#f85149'; el.textContent += ' — STALE'; }
  }
  tick(); setInterval(tick, 30000);
"""


def render(scan: dict, led: pd.DataFrame, paper: dict | None, live: dict | None,
           run_log: list | None) -> str:
    """The whole page as a string. Every argument may be empty/None; nothing here raises."""
    scan = scan if isinstance(scan, dict) else {}
    survivors = [s for s in (scan.get("survivors") or []) if isinstance(s, dict)]
    champ = scan.get("champion") if isinstance(scan.get("champion"), dict) else {}
    band = str(scan.get("band") or champ.get("entry_band") or config.DEFAULT_ENTRY_BAND)
    exit_name = str(champ.get("exit") or config.IMPROVE_DEFAULT_EXIT_CHAMPION)
    scan_ts = _num(scan.get("scan_ts"), 0.0)
    n_a = sum(1 for s in survivors if s.get("tier") == "A")
    trigger = scan.get("trigger")
    run_s = _num(scan.get("run_seconds"))
    stamp_bits = [f"scanned {int(_num(scan.get('discovered'), 0))}",
                  f"enriched {int(_num(scan.get('enriched'), 0))}",
                  f"{len(survivors)} passed gates",
                  f'<span id="ago" data-ts="{scan_ts:.0f}" data-stale="{STALE_MINUTES}">…</span>']
    tail_bits = []
    if trigger:
        tail_bits.append(f"trigger {_esc(trigger, 12)}")
    if run_s is not None:
        tail_bits.append(f"run {_fmt_secs(run_s)}")
    gm_cov = _num(scan.get("gmgn_coverage"))
    if gm_cov is not None:                 # how far the Trenches feed reaches into this run's survivors
        tail_bits.append(f"GMGN coverage {gm_cov:.0%}")
    tail_bits.append(f"auto-reloads every {META_REFRESH_S // 60}&nbsp;min")

    a_html = _safe(lambda: _cards(survivors, "A", band))
    b_html = _safe(lambda: _cards(survivors, "B", band))
    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="{META_REFRESH_S}">
<title>robinhood_screener</title>
<style>{_CSS}</style></head><body>
<h1>robinhood_screener <small style="color:#8b949e;font-size:13px;font-weight:400">Robinhood Chain · id {config.CHAIN_ID}</small></h1>
<div class="stamp">{' · '.join(stamp_bits)}</div>
<div class="stamp">{' · '.join(tail_bits)}</div>
{_safe(lambda: _runs_line(scan, run_log or []))}
<div class="stamp">entry band <b>{_esc(band, 40)}</b> · exit plan <b>{_esc(exit_name, 40)}</b></div>
<h2>Source health (this scan)</h2>{_safe(lambda: _health_chips(scan))}
<h2>A-tier (alerted · {_esc(band, 40)})</h2>{a_html}
<h2>B-tier survivors (ledgered as the control, never alerted)</h2>{b_html}
<h2>Discovery by source</h2>{_safe(lambda: _discovery(scan))}
<h2>Honest scorecard (A vs B)</h2>{_safe(lambda: _scorecard(led))}
<h2>Paper A-book (cloud, quotes only)</h2>{_safe(lambda: _paper_book(paper or {}))}
<h2>Live paper book (Mac, multi-policy)</h2>{_safe(lambda: _livebook(live))}
<footer>{html.escape(config.FOOTER)} Ranked by survival-quality score, NOT predicted ROI.</footer>
<script>{_JS}</script>
</body></html>"""


def write_page(page: str, out: str) -> None:
    """tmp + os.replace so Pages never serves a half-written file."""
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    tmp = f"{out}.{os.getpid()}.tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(page)
    os.replace(tmp, out)


def main() -> str:
    """Render the committed data to config.DOCS_DIR/index.html and return the path."""
    scan, led, paper, live, run_log = load_inputs()
    out = os.path.join(config.DOCS_DIR, "index.html")
    write_page(render(scan, led, paper, live, run_log), out)
    print(f"dashboard written: {out}  ({os.path.getsize(out):,} bytes; "
          f"{len(scan.get('survivors') or [])} survivors, {len(led)} ledger rows, "
          f"{len(run_log)} run-log lines)")
    return out


if __name__ == "__main__":
    import tempfile
    # Offline smoke test: synthetic scan (one A, one B), an empty ledger on a temp path, no paper
    # files, a 3-line run log. Writes ONLY to a temp dir unless --write is passed.
    t0 = 1_800_000_000.0
    base = {"liq_usd": 45_000.0, "mcap": 250_000.0, "vol_h24": 120_000.0, "pair_age_min": 180.0,
            "total_holders": 1400, "holders_source": "blockscout", "top10_pct": 18.0,
            "lp_locked_pct": 100.0, "lp_check_source": "rpc_v2", "roundtrip_loss_pct": 4.8,
            "sources_dark": []}
    scan = {"scan_ts": t0, "trigger": "dispatch", "band": config.DEFAULT_ENTRY_BAND,
            "champion": {"exit": config.IMPROVE_DEFAULT_EXIT_CHAMPION,
                         "entry_band": config.DEFAULT_ENTRY_BAND},
            "champion_na_frac": 0.5, "discovered": 37, "enriched": 31, "absent": 4,
            "by_source": {"logs": 20, "watchlist": 9, "rechecks": 6, "feeds": 2},
            "quota_cuts": {"logs": 3}, "deferred_by_stage": {"pass2": 2},
            "pass1_rejects_by_gate": {"liq_ok": 14, "vol_ok": 9, "owner_ok": 3},
            "survivors": [
                dict(base, symbol="MIZU<b>", token=config.MIZUKARA, score=84.0, tier="A",
                     url="https://dexscreener.com/robinhood/x", event_kind="promotion", event_seq=7,
                     hc_misses=[], champion_reason="", plan_line="PLAN [champion cfg_ladder_stop]: "
                     "buy ~$10 · hard-stop -50% · TP 2x→sell 50%, 5x→sell 25%, 10x→sell 15%",
                     bands={config.DEFAULT_ENTRY_BAND: 1, "score60": 1, "graduated_1h": "NA"}),
                dict(base, symbol="BEE", token="0xbee", score=61.0, tier="B", url="",
                     event_kind="first_sighting", event_seq=8, total_holders=1500,
                     holders_source="gt", sources_dark=["blockscout"],
                     hc_misses=["unknown: holders below 1000 (or not exact)"],
                     champion_reason="unknown: holders below 1000 (or not exact); score below 70",
                     bands={config.DEFAULT_ENTRY_BAND: "NA", "score60": 1}),
            ],
            "health": {"api.dexscreener.com": {"ok": 12, "fail": 0, "absent": 1, "bot_challenge": False,
                                               "last_status": None},
                       "robinhoodchain.blockscout.com": {"ok": 0, "fail": 2, "absent": 0,
                                                         "bot_challenge": True, "last_status": 403},
                       "api.geckoterminal.com": {"ok": 3, "fail": 1, "absent": 0,
                                                 "bot_challenge": False, "last_status": 429}},
            "run_seconds": 88.4}
    run_log = [{"scan_ts": t0 - 2 * 86400, "trigger": "schedule", "run_seconds": 40, "n_a": 1},
               {"scan_ts": t0 - 600, "trigger": "schedule", "run_seconds": 120.0, "n_a": 0,
                "deferred": 1},
               {"scan_ts": t0, "trigger": "dispatch", "run_seconds": 88.4, "n_a": 1}]
    with tempfile.TemporaryDirectory() as d:
        led = ledger.load(os.path.join(d, "ledger.csv"))        # empty, schema columns present
        assert len(led) == 0 and list(led.columns) == ledger.COLUMNS
        page = render(scan, led, None, None, run_log)
        for needle in ("A-TIER", config.DEFAULT_ENTRY_BAND, "runs in the last 24 h", config.FOOTER,
                       "Ranked by survival-quality score, NOT predicted ROI",
                       "If tier A doesn't clearly beat tier B, the A-band is not adding signal",
                       "Real automation is justified ONLY if this scorecard is repeatedly positive",
                       "the live paper book runs on the Mac; a summary is published weekly",
                       'http-equiv="refresh" content="300"', 'data-stale="30"',
                       "BOT-CHALLENGED", "degraded", "short of band_a_strict:",
                       "champion band was NA", "MIZU&lt;b&gt;"):
            assert needle.lower() in page.lower(), f"missing: {needle}"
        assert "MIZU<b>" not in page, "symbol must be HTML-escaped"
        # the 24 h window is anchored on the last scan_ts: 2 of 3 lines qualify
        assert "runs in the last 24 h: <b>2</b> (dispatch 1 / schedule 1)" in page, page[:0]
        assert "median run 104s" in page
        # every section still renders on garbage / empty inputs, never raises
        junk = render({"survivors": [None, 3, {"tier": "A", "score": "x"}], "health": "no"},
                      None, {"fills": [None], "positions": {"k": None}}, {"per_policy": 5}, [{}, 7])
        assert "A-TIER" in junk and config.FOOTER in junk
        empty = render({}, led, {}, None, [])
        assert "No A-tier coins this scan" in empty and "none logged yet" in empty
        # a populated ledger + paper book + livebook exercise the remaining sections
        p = os.path.join(d, "led.csv")
        ledger.record_rows([{"token": "0xabc", "symbol": "DEMO", "tier": "B", "event_kind": "first_sighting",
                             "market": {"price_usd": 1.0, "mcap": 1e6, "liq_usd": 5e4}, "score": 55.0},
                            {"token": "0xdef", "symbol": "DEMO2", "tier": "A", "event_kind": "promotion",
                             "market": {"price_usd": 1.0, "mcap": 1e6, "liq_usd": 5e4}, "score": 80.0}],
                           alert_ts=t0 - 90000, path=p)
        snap = lambda toks: {"ok": {t: {"price_usd": 0.5, "mcap": 5e5, "liq_usd": 5e4} for t in toks},
                             "absent": set(), "deferred": set()}
        ledger.update_forward(t0, snap, path=p)
        paper = {"fills": [{"side": "buy", "impact_pct": "1.2", "gas_usd": "0.07", "quote_status": "ok"},
                           {"side": "sell", "impact_pct": "0.9", "gas_usd": "0.07", "quote_status": "ok"}],
                 "positions": {"0xdef:2": {"symbol": "DEMO2", "cost_usd": 10.0, "realized_usd": 6.0,
                                           "closed": True},
                               "0xghi:3": {"symbol": "X", "cost_usd": 10.0, "realized_usd": 0.0,
                                           "closed": False}}}
        live = {"ts": t0 - 3600, "champion": "cfg_ladder_stop", "n_positions": 12, "n_days": 4,
                "per_policy": {"sell_1h": {"n": 12, "mean": 0.12, "day_lb": -0.3},
                               "cfg_ladder_stop": {"n": 12, "mean": -0.2, "day_lb": -0.6}},
                "controls": {"ctl_exit_immediately": {"n": 12, "mean": -0.03, "day_lb": -0.05}},
                "nomination": None, "note": "below IMPROVE_MIN_POSITIONS; nothing decided"}
        full = render(scan, ledger.load(p), paper, live, run_log)
        assert "A (alerted)" in full and "B (silent control)" in full and "n=1" in full
        assert "1 open · 1 closed" in full and "mean entry impact" in full and "1.20%" in full
        assert "sell_1h" in full and "(control)" in full
        out = os.path.join(d, "index.html")
        write_page(page, out)
        print(f"smoke page written: {out}  ({os.path.getsize(out):,} bytes)")
        print(f"full page (ledger + paper + livebook): {len(full):,} bytes; "
              f"empty page: {len(empty):,} bytes")
    print("assertions hold: A/B cards, escaping, 24 h window anchored on scan_ts, honest notes, "
          "garbage inputs degrade without raising")
    if "--write" in sys.argv:
        main()
    else:
        print("(pass --write to render the committed data to docs/index.html)")
